Added Swagger docs for legacy endpoints
ixofoundation/ixo-blockchain pull request #245
Opened 2021-08-19 10:29 UTC by stefaniatadama

2021-09-10 07:32 UTC, migueldingli1997 commented on client/docs/swagger-ui-legacy/swagger.yaml
> +  version: 1.0.0
```suggestion
info:
  title: ixo modules - legacy endpoints docs
  description: A REST interface for state queries
  version: 1.0.0
host: testnet.ixo.world
basePath: /rest
schemes:
  - https
```

2021-09-10 08:37 UTC, migueldingli1997 requested changes
- Requested some changes here https://github.com/ixofoundation/ixo-blockchain/pull/248
- We have a lot of definitions in swagger.yaml but did not use them throughout
- The order of endpoints can be improved. For example; `/batch` can be next to `/last_batch`

2021-09-15 14:22 UTC, stefaniatadama commented
- Requested changes were merged to this branch
- Unused definitions were removed
- Order of endpoints was changed (previously ordered alphabetically)

2021-09-16 09:39 UTC, migueldingli1997 approved these changes

2021-09-16 09:39 UTC, merged